dictionaryDefinitions:
  - name: DeepValve an automatic detection pipeline for the mitral valve in cardiac magnetic resonance imaging
    path: .cspell_dict.txt
    addWords: true
dictionaries:
  - DeepValve: an automatic detection pipeline for the mitral valve in cardiac magnetic resonance imaging
ignoreWords: [
    tableofcontents,
    ipynb,
    oneline
  ]

{
  "version": "0.2",
  "language": "en",
  "words": [],
  "ignorePaths": ["node_modules", "dist"]
}