# # Simple workflow for deploying static content to GitHub Pages
# name: Build docs

# on:
#   workflow_dispatch:
#   workflow_call:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build_docs:
#     runs-on: ubuntu-22.04
#     env:
#       PYTHON_VERSION: "3.10"
#       PUBLISH_DIR: ./_build/html

#     steps:
#       # checkout the repository
#       - uses: actions/checkout@v4

#       # setup Python
#       - name: Install Python ${{ env.PYTHON_VERSION }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ env.PYTHON_VERSION }}

#       # preserve pip cache to speed up installation
#       - name: Cache
#         id: cache
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.cache/pip
#             ~/_build
#           key: cache_v1
#           restore-keys: |
#             cache_v1

#       - name: Install Python dependencies
#         run: |
#           python3 -m pip install --upgrade pip
#           python3 -m pip install ".[docs]"

#       - name: Build docs
#         run: python3 -m jupyter book build .

#       - name: Upload artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: documentation
#           path: ${{ env.PUBLISH_DIR }}

# Simple workflow for deploying static content to GitHub Pages
name: Build docs

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-24.04
    env:
      PUBLISH_DIR: ./_build/html

    steps:
      # checkout the repository
      - uses: actions/checkout@v5

      # setup Python
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --extra docs

      - name: Build docs
        run: uv run jupyter book build .

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}